//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewLetter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class courseType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public courseType()
        {
            this.courseSpecializations = new HashSet<courseSpecialization>();
            this.qendidateGraduations = new HashSet<qendidateGraduation>();
            this.qendidatePGraduations = new HashSet<qendidatePGraduation>();
        }
    
        public long courseTypeID { get; set; }
        public int educationTypeID { get; set; }
        public string courseName { get; set; }
        public System.DateTime dataIscCreated { get; set; }
        public System.DateTime dataIsUpdated { get; set; }
        public bool isActive { get; set; }
        public long createdBy { get; set; }
        public long modifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<courseSpecialization> courseSpecializations { get; set; }
        public virtual educationType educationType { get; set; }
        public virtual EmployerDetail EmployerDetail { get; set; }
        public virtual EmployerDetail EmployerDetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qendidateGraduation> qendidateGraduations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qendidatePGraduation> qendidatePGraduations { get; set; }
    }
}
