//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewLetter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qendidatePGraduation
    {
        public long pggradid { get; set; }
        public long qenID { get; set; }
        public string collegeName { get; set; }
        public string collegeUniversity { get; set; }
        public Nullable<long> courseName { get; set; }
        public Nullable<long> courseField { get; set; }
        public string pgradPercentageorGrade { get; set; }
        public Nullable<System.DateTime> dataIsCreated { get; set; }
        public Nullable<System.DateTime> dataIsUpdated { get; set; }
        public Nullable<int> YearPassing { get; set; }
        public string city { get; set; }
        public Nullable<int> educationTypeID { get; set; }
    
        public virtual courseSpecialization courseSpecialization { get; set; }
        public virtual courseType courseType { get; set; }
        public virtual educationType educationType { get; set; }
        public virtual qendidateList qendidateList { get; set; }
    }
}
