//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewLetter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qenReference
    {
        public long qenID { get; set; }
        public long qenRefID { get; set; }
        public string qenRefName { get; set; }
        public string qenRefCompany { get; set; }
        public Nullable<double> qenRefPhone { get; set; }
        public string qenRefEmail { get; set; }
        public string qenRefPosition { get; set; }
        public Nullable<System.DateTime> dataIsCreated { get; set; }
        public Nullable<System.DateTime> dataIsUpdated { get; set; }
        public bool isDelete { get; set; }
        public bool isCheckComplete { get; set; }
    
        public virtual qendidateList qendidateList { get; set; }
    }
}
