//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewLetter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_qenlist
    {
        public long qenID { get; set; }
        public string qenName { get; set; }
        public string qenEmail { get; set; }
        public string qenLinkdInUrl { get; set; }
        public string qenPhone { get; set; }
        public string qenNationality { get; set; }
        public string qenPassport { get; set; }
        public Nullable<System.DateTime> dataIsCreated { get; set; }
        public Nullable<System.DateTime> dataIsUpdated { get; set; }
        public int roleID { get; set; }
        public bool isDelete { get; set; }
        public bool isActive { get; set; }
        public string password { get; set; }
        public string qenResume { get; set; }
        public string qenCoverLetter { get; set; }
        public Nullable<bool> IsReferenceCleared { get; set; }
        public string qenImage { get; set; }
        public Nullable<int> genderID { get; set; }
        public string CareerObjective { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public bool socialCheck { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public string City { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string streetNo { get; set; }
        public string qenAddress { get; set; }
        public string zipCode { get; set; }
        public string CareerHighlight { get; set; }
        public Nullable<System.DateTime> lastLoginTime { get; set; }
        public string genderName { get; set; }
    }
}
